dist: trusty
sudo: required
services:
  - mysql
matrix:

  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd Backend/
        - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\nCREATE DATABASE proj_eszk CHARACTER SET latin1 COLLATE latin1_swedish_ci\n" | mysql -u root -p root
        - echo "SETTING MYSQL CREDENTIALS..."
        - gradle update -PrunList=migrate
        - echo "GRADLE ASSEMBLE..."
        - gradle assemble

      script:
        - gradle test
      addons:
        apt:
          sources:
            - mysql-5.7-trusty
          packages:
            - mysql-server
            - mysql-client
      before_install:
        - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo mysql_upgrade -uroot -proot
        - sudo service mysql restart

      after_success:
        - gradle build

    - language: node_js
      node_js:
        - 'node'

      addons:
        apt:
          sources:
            - google-chrome
            - mysql-5.7-trusty
          packages:
            - google-chrome-stable
            - google-chrome-beta
            - mysql-server
            - mysql-client

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      before_script:
        - cd Frontend/
        - npm install -g angular-cli
        - npm install -g karma
        - npm install -g protractor
        - npm install
        - ng build

      script: ng e2e
      after_success:
        - ng build