dist: trusty
sudo: required
services:
  - mysql
matrix:
  
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd Backend/
        - echo "SETTING MYSQL CREDENTIALS..."
        - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\nCREATE DATABASE proj_esk" | mysql -u root
        - gradle update -PrunList=migrate
        - echo "GRADLE ASSEMBLE..."
        - gradle assemble
      script:
        - gradle test
      after_success:
        - gradle build

    - language: node_js
      node_js:
        - 'node'

      addons:
      apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable
        - google-chrome-beta

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - 

      before_script:
        - cd Frontend/
        - npm install -g angular-cli
        - npm install -g karma
        - npm install -g protractor
        - npm install
        - ng build

      script: ng e2e
      after_success:
        - ng build